// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjnwkL1T7mRB8afu7Eu6QbmbJ0VpRMpgU',
    appId: '1:1067200594875:web:02a8e8c7c039737c8efa9e',
    messagingSenderId: '1067200594875',
    projectId: 'chat-app-a9660',
    authDomain: 'chat-app-a9660.firebaseapp.com',
    storageBucket: 'chat-app-a9660.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeC_mBQaAtRupziJhHm08Tzd4PRvVk5Oo',
    appId: '1:1067200594875:android:30a7998203311c648efa9e',
    messagingSenderId: '1067200594875',
    projectId: 'chat-app-a9660',
    storageBucket: 'chat-app-a9660.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcEJmC8n6RwdTx1UFaQqE6eNPYBFBJ3Oc',
    appId: '1:1067200594875:ios:964d03a95cfb8b2a8efa9e',
    messagingSenderId: '1067200594875',
    projectId: 'chat-app-a9660',
    storageBucket: 'chat-app-a9660.appspot.com',
    iosClientId: '1067200594875-9a2emthbu9quqkjtgjisr6e0g7eevhft.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningPhoneAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcEJmC8n6RwdTx1UFaQqE6eNPYBFBJ3Oc',
    appId: '1:1067200594875:ios:deb98e1cdbcbfa478efa9e',
    messagingSenderId: '1067200594875',
    projectId: 'chat-app-a9660',
    storageBucket: 'chat-app-a9660.appspot.com',
    iosClientId: '1067200594875-467ipcl4h438ccgjnopl8sed1qmm17os.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningPhoneAuthentication.RunnerTests',
  );
}
